name: Deploy Static Site to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::376715672817:role/orioncor-website-deploy
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://orioncor-website-hosting --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ECQSKVMGITSOQ \
            --paths "/*"
